import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Instagram } from 'react-feather'
import { ICard } from '../components/card'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
    console.log(styles)
    return (
        <>
            <Head>
                <title>pH da quimica</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <Image
                    src={'/logoWhite.png'}
                    alt="logo"
                    width={548}
                    height={548}
                    className={styles.logo}
                />
                <Link href="/curso" className={styles.loginButton}>
                    ENTRAR
                </Link>
            </div>
        </>
    )
}
